import os
import sys
import json
import logging

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

from pathlib import Path
from dotenv import load_dotenv

_env_path = Path(__file__).with_name(".env")
if _env_path.exists():
    load_dotenv(_env_path)
else:
    load_dotenv()

import sentry_sdk
_sentry_dsn = os.getenv("SENTRY_DSN", "").strip()
if _sentry_dsn:
    sentry_sdk.init(
        dsn=_sentry_dsn,
        environment=os.getenv("SENTRY_ENVIRONMENT", "development"),
        send_default_pii=False,
        traces_sample_rate=0.0,
    )
    print("[Sentry] error monitoring enabled")
else:
    print("[Sentry] SENTRY_DSN not configured, skipping (local logs only)")

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from datetime import datetime, timezone
from typing import Optional, Any
import uvicorn

from protocol import generate_protocol
from analyze import analyze_dataset
from report import generate_report as build_report

app = FastAPI(
    title="DataLab AI Backend",
    description="DataLab AI Experiment Workflow Platform Backend API",
    version="0.2.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class HealthResponse(BaseModel):
    status: str
    message: str
    timestamp: str
    version: str


class StatColumn(BaseModel):
    min: Optional[float] = None
    max: Optional[float] = None
    mean: Optional[float] = None
    median: Optional[float] = None

class IssueItem(BaseModel):
    type: str
    severity: str
    row_index: Optional[int] = None
    column: Optional[str] = None
    message: str
    value: Optional[Any] = None

class AIExplanation(BaseModel):
    possible_causes: list[str]
    suggested_actions: list[str]
    impact_on_conclusion: str
    confidence: str

class AnalysisInput(BaseModel):
    dataset_name: str
    row_count: int
    column_count: int
    quality_score: float
    quality_level: str
    issues: list[IssueItem]
    statistics: dict[str, StatColumn]
    ai_explanation: AIExplanation


class VariableItem(BaseModel):
    name: str
    unit: str
    type: str
    required: bool

class ProtocolInput(BaseModel):
    title: str
    objective: str
    assumptions: list[str]
    equipment: list[str]
    variables: list[VariableItem]
    sampling_frequency: str
    expected_interval_minutes: Optional[float] = None
    expected_duration_minutes: Optional[float] = None
    procedure_steps: list[str]
    control_conditions: list[str]
    possible_errors: list[str]
    csv_template: str


class ReportRequest(BaseModel):
    protocol: Optional[dict] = None
    analysis: Optional[dict] = None
    user_requirements: Optional[str] = None

class ReportSections(BaseModel):
    introduction: str
    method: str
    results: str
    discussion: str
    conclusion: str

class ReportResponse(BaseModel):
    title: str
    markdown: str
    sections: ReportSections
    generated_from: dict
    warnings: list[str]


def _fmt_stats(analysis: AnalysisInput) -> str:
    lines = []
    for col, s in analysis.statistics.items():
        parts = []
        if s.min    is not None: parts.append(f"min={s.min:.4g}")
        if s.max    is not None: parts.append(f"max={s.max:.4g}")
        if s.mean   is not None: parts.append(f"mean={s.mean:.4g}")
        if s.median is not None: parts.append(f"median={s.median:.4g}")
        if parts:
            lines.append(f"  - {col}: {', '.join(parts)}")
    return "\n".join(lines) if lines else "  (no statistics)"


def _fmt_issues(analysis: AnalysisInput) -> str:
    if not analysis.issues:
        return "  (no quality issues)"
    return "\n".join(
        f"  - [{i.severity}] {i.message}"
        for i in analysis.issues[:10]
    )


def _assemble_markdown(title: str, s: ReportSections, footer: str) -> str:
    return f"""# {title}

## 1. Introduction

{s.introduction}

## 2. Method

{s.method}

## 3. Results

{s.results}

## 4. Discussion

{s.discussion}

## 5. Conclusion

{s.conclusion}

---

*{footer}*
"""


def _fallback_report(
    protocol: Optional[ProtocolInput],
    analysis: Optional[AnalysisInput],
    warnings: list[str],
) -> ReportResponse:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    title = protocol.title if protocol else "Experiment Report (Demo Template)"

    if protocol:
        intro = (
            f"This experiment aims to {protocol.objective}. "
            f"Experimental assumptions include: {'; '.join(protocol.assumptions[:3])}."
        )
    else:
        intro = (
            "This report was automatically generated by DataLab AI. "
            "Since no protocol was provided, the introduction is limited. "
            "Please add a protocol and regenerate."
        )

    if protocol:
        vars_desc = ", ".join(f"{v.name} ({v.unit})" for v in protocol.variables)
        steps_desc = "\n".join(
            f"{i+1}. {step}" for i, step in enumerate(protocol.procedure_steps)
        )
        method = (
            f"**Equipment**: {', '.join(protocol.equipment)}.\n\n"
            f"**Variables**: {vars_desc}.\n\n"
            f"**Sampling Frequency**: {protocol.sampling_frequency}.\n\n"
            f"**Procedure Steps**:\n{steps_desc}\n\n"
            f"**Control Conditions**: {'; '.join(protocol.control_conditions)}."
        )
    else:
        method = (
            "No protocol provided; the Method section cannot be auto-generated. "
            "Please complete the protocol design and regenerate the report."
        )

    if analysis:
        stat_lines = []
        for col, s in analysis.statistics.items():
            parts = []
            if s.mean is not None: parts.append(f"mean **{s.mean:.4g}**")
            if s.min is not None and s.max is not None:
                parts.append(f"range [{s.min:.4g}, {s.max:.4g}]")
            if s.median is not None: parts.append(f"median {s.median:.4g}")
            if parts:
                stat_lines.append(f"- **{col}**: {', '.join(parts)}")

        stat_block = "\n".join(stat_lines) if stat_lines else "(no column statistics yet)"
        high_cnt = sum(1 for i in analysis.issues if i.severity == "high")
        issue_note = (
            f"including {high_cnt} high-severity issues" if high_cnt else "all low/medium severity"
        )

        results = (
            f"Dataset **{analysis.dataset_name}**: {analysis.row_count} rows, "
            f"{analysis.column_count} columns. Data quality score: **{analysis.quality_score:.1f} / 100** "
            f"(level: {analysis.quality_level}).\n\n"
            f"**Column Statistics Summary**:\n{stat_block}\n\n"
            f"Data quality check found **{len(analysis.issues)}** issues ({issue_note}).\n\n"
            f"AI confidence: **{analysis.ai_explanation.confidence}**. "
            f"Impact on conclusion: {analysis.ai_explanation.impact_on_conclusion}"
        )
    else:
        results = (
            "No analysis data provided; this section cannot include specific experimental values. "
            "Please complete the data analysis step and regenerate to obtain a Results section with real statistics."
        )

    if analysis and analysis.ai_explanation.possible_causes:
        causes  = "; ".join(analysis.ai_explanation.possible_causes[:3])
        actions = "; ".join(analysis.ai_explanation.suggested_actions[:3])
        discussion = (
            f"**Possible causes of data anomalies**: {causes}.\n\n"
            f"**Suggested improvements**: {actions}."
        )
    elif protocol and protocol.possible_errors:
        errs = ", ".join(protocol.possible_errors[:4])
        discussion = (
            f"Potential sources of error in this experiment include: {errs}. "
            "It is recommended to control these in future experiments to improve data reliability."
        )
    else:
        discussion = (
            "Due to limited data, the Discussion section cannot provide in-depth analysis. "
            "Please add more experimental data and regenerate."
        )

    if analysis:
        q = analysis.quality_level
        if q in ("Excellent", "Good"):
            qual_note = "The experimental results are highly reliable and can serve as a reference for further research."
        else:
            qual_note = (
                f"⚠️ Note: Data quality level is {q}; conclusions carry uncertainty. "
                "It is recommended to address data quality issues before drawing final conclusions."
            )
        conclusion = (
            f"In summary, the data quality score is {analysis.quality_score:.1f}/100 ({q}). "
            f"{qual_note} "
            "Future research can expand the sample size to further verify the experimental hypothesis."
        )
    else:
        conclusion = (
            "Due to the lack of complete experimental data, no definitive conclusion can be drawn at this time. "
            "Please complete data collection and analysis, then regenerate the report to obtain a data-supported conclusion."
        )

    sections = ReportSections(
        introduction=intro,
        method=method,
        results=results,
        discussion=discussion,
        conclusion=conclusion,
    )
    footer = f"Auto-generated by DataLab AI (template mode) · {now}"

    return ReportResponse(
        title=title,
        markdown=_assemble_markdown(title, sections, footer),
        sections=sections,
        generated_from={
            "has_protocol": protocol is not None,
            "has_analysis": analysis is not None,
            "dataset_name": analysis.dataset_name if analysis else None,
        },
        warnings=warnings,
    )


def _call_claude(
    protocol: Optional[ProtocolInput],
    analysis: Optional[AnalysisInput],
    user_requirements: Optional[str],
) -> dict:
    from anthropic import Anthropic
    client = Anthropic()

    ctx_parts: list[str] = []

    if protocol:
        vars_str = ", ".join(f"{v.name}({v.unit})" for v in protocol.variables)
        steps_str = "\n".join(
            f"  {i+1}. {s}" for i, s in enumerate(protocol.procedure_steps)
        )
        ctx_parts.append(f"""
=== Protocol ===
Title: {protocol.title}
Objective: {protocol.objective}
Assumptions: {'; '.join(protocol.assumptions)}
Equipment: {', '.join(protocol.equipment)}
Variables: {vars_str}
Sampling Frequency: {protocol.sampling_frequency}
Expected Duration: {protocol.expected_duration_minutes} min
Procedure Steps:
{steps_str}
Control Conditions: {'; '.join(protocol.control_conditions)}
Possible Errors: {'; '.join(protocol.possible_errors)}
""")

    if analysis:
        ctx_parts.append(f"""
=== Analysis (Real Data — Results must only cite these values, no fabrication) ===
Dataset: {analysis.dataset_name}
Rows: {analysis.row_count}, Columns: {analysis.column_count}
Quality Score: {analysis.quality_score:.1f}/100 ({analysis.quality_level})
Column Statistics (Real Data):
{_fmt_stats(analysis)}
Data Quality Issues ({len(analysis.issues)} total):
{_fmt_issues(analysis)}
AI Interpretation:
  Possible Causes: {'; '.join(analysis.ai_explanation.possible_causes)}
  Suggested Actions: {'; '.join(analysis.ai_explanation.suggested_actions)}
  Impact on Conclusion: {analysis.ai_explanation.impact_on_conclusion}
  Confidence: {analysis.ai_explanation.confidence}
""")

    if not ctx_parts:
        ctx_parts.append("(No experimental data provided — generate a framework based on general scientific writing conventions)")

    data_ctx = "\n".join(ctx_parts)

    user_req_block = (
        f"\nUser additional formatting requirements: {user_requirements}" if user_requirements else ""
    )

    system = """You are a rigorous scientific experiment report writing assistant. Generate a five-chapter academic report based on real experimental data.

[Strict Rules — violation invalidates the report]
1. All specific values in the Results chapter (mean, min, max, median, row count, quality score, etc.) must and can only come from the numbers in the user-provided "Real Data" block. Do not estimate, infer, or fabricate.
2. If analysis data is missing, the Results chapter must explicitly state "No analysis data provided; specific values cannot be given" — do not fabricate any numbers.
3. The Conclusion may only summarize what the Results data supports. If quality_level is Risky or Poor, note the data quality limitations in the Conclusion.
4. Write entirely in English. Use objective, rigorous academic language.
5. Output only the body text for each chapter — do not include chapter headings (they are added automatically).

[Chapter Writing Rules]
- Introduction: Based on protocol.objective, explain the experimental background, purpose, and scientific hypothesis.
- Method: Based on protocol.equipment, variables, sampling_frequency, and procedure_steps, describe the experimental design.
- Results: Based on analysis.quality_score, analysis.statistics, and analysis.issues, list statistics per variable (format: variable name mean/range/median) and describe data quality.
- Discussion: Based on protocol.possible_errors, analysis.issues, and ai_explanation, analyze causes of anomalies and experimental limitations.
- Conclusion: Summarize only what the data supports; note quality limitations when level is low.

[Output Format]
Return a plain JSON object. Field values are text with Markdown inline formatting (**bold**, - lists), no # headings:
{
  "introduction": "...",
  "method": "...",
  "results": "...",
  "discussion": "...",
  "conclusion": "..."
}
Do not include any ```json``` code block markers — output raw JSON only.
IMPORTANT: All output must be in English only. Do not use any Chinese characters."""

    user_msg = f"""Please generate the five chapters of the experiment report based on the following data:

{data_ctx}{user_req_block}

Strictly follow all rules and return only JSON."""

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=8000,
        system=system,
        messages=[{"role": "user", "content": user_msg}],
    )

    raw = resp.content[0].text.strip()

    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1]
        raw = raw.rsplit("```", 1)[0].strip()

    result = json.loads(raw)

    required = {"introduction", "method", "results", "discussion", "conclusion"}
    missing = required - set(result.keys())
    if missing:
        raise ValueError(f"Claude 返回 JSON 缺少字段：{missing}")

    return result


@app.get("/api/health", response_model=HealthResponse)
async def health_check() -> HealthResponse:
    return HealthResponse(
        status="ok",
        message="DataLab AI backend service is running normally",
        timestamp=datetime.now(timezone.utc).isoformat(),
        version="0.2.0",
    )


class ProtocolRequest(BaseModel):
    goal: str
    constraints: Optional[str] = None


@app.post("/api/protocol")
async def create_protocol(req: ProtocolRequest) -> dict:
    return generate_protocol(goal=req.goal, constraints=req.constraints)


class AnalyzeRequest(BaseModel):
    csv_text: str = ""
    dataset_name: str = "experiment.csv"
    protocol_context: Optional[str] = None
    input_kind: str = "text"
    file_base64: Optional[str] = None
    media_type: Optional[str] = None
    experiment_steps: Optional[str] = None


@app.post("/api/analyze")
async def create_analysis(req: AnalyzeRequest) -> dict:
    result = analyze_dataset(
        csv_text=req.csv_text,
        dataset_name=req.dataset_name,
        protocol_context=req.protocol_context,
        input_kind=req.input_kind,
        file_base64=req.file_base64,
        media_type=req.media_type,
        experiment_steps=req.experiment_steps,
    )
    if not result["ok"]:
        raise HTTPException(status_code=400, detail=result["error"])
    return result["data"]


@app.get("/")
async def root() -> dict:
    return {"name": "DataLab AI Backend", "docs": "/docs", "health": "/api/health"}


@app.post("/api/report")
async def generate_report(req: ReportRequest) -> dict:
    return build_report(
        protocol=req.protocol,
        analysis=req.analysis,
        user_requirements=req.user_requirements,
    )


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
